apiVersion: v1
kind: Service
metadata:
  name: mywebapi-service
spec:
  type: NodePort
  selector:
    app: mywebapi
  ports:
    - name: mywebapi
      protocol: TCP
      port: 80
      targetPort: 80